import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#3f4940',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#6f7a6f',
        'outline-variant': '#becabd',
        'surface-tint': '#016d38',
        primary: '#006030',
        'on-primary': '#ffffff',
        'primary-container': '#1b7a43',
        'on-primary-container': '#abffbf',
        'inverse-primary': '#80d998',
        secondary: '#a23f00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fc7127',
        'on-secondary-container': '#5c2000',
        tertiary: '#5333c9',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6c50e3',
        'on-tertiary-container': '#efe8ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f8',
        'on-background': '#1b1c1c',
      },
      fontFamily: {
        sans: ['var(--font-public-sans)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '500' }],
        'body-md': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.05em', fontWeight: '700' }],
        'big-number': ['48px', { lineHeight: '52px', fontWeight: '800' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '20px',
        lg: '32px',
        xl: '48px',
        'touch-target': '56px',
      },
    },
  },
  plugins: [],
};

export default config;
